language: node_js
node_js:
  - "iojs"
  - "7"
deploy:
  provider: s3
  access_key_id: "AKIAJZJDHU47DUYXRB4A"
  secret_access_key: "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"
  bucket: "try-step1"
  skip_cleanup: true

